Sil\Bundle\CRMBundle\Entity\Address:
    type: mappedSuperclass

    fields:
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
        postCode:
            type: string
            nullable: true
        street:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        countryCode:
            type: string
        provinceCode:
            type: string
            nullable: true
        provinceName:
            type: string
            nullable: true
        npai:
            type: boolean
            default: false
        vcardUid:
            type: string
            nullable: true
        confirmed:
            type: boolean
            default: true
