Librinfo\CRMBundle\Entity\Address:
    type: entity

    fields:
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
        postCode:
            type: string
            nullable: true
        street:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        countryCode:
            type: string
        provinceCode:
            type: string
            nullable: true
        provinceName:
            type: string
            nullable: true
        npai:
            type: boolean
            default: false
        vcardUid:
            type: string
            nullable: true
        confirmed:
            type: boolean
            default: true

    manyToOne:
        organism:
            targetEntity: Librinfo\CRMBundle\Entity\Organism
            inversedBy: addresses
            joinColumn:
                name: organism_id
                referencedColumnName: id
                nullable: true
                onDelete: SET NULL
#            cascade: [ persist]