Librinfo\CRMBundle\Entity\Address:
    type: entity

    fields:
        firstName:
            type: string
            nullable: true
        lastName:
            type: string
            nullable: true
        postCode:
            type: string
            nullable: true
        street:
            type: string
            nullable: true
        city:
            type: string
            nullable: true
        countryCode:
            type: string
        provinceCode:
            type: string
            nullable: true
        provinceName:
            type: string
            nullable: true
        npai:
            type: boolean
            default: false
        vcardUid:
            type: string
            nullable: true
        confirmed:
            type: boolean
            default: true

    manyToOne:
        contact:
            targetEntity: Librinfo\CRMBundle\Entity\Contact
            inversedBy: addresses
            joinColumn:
                name: contact_id
                referencedColumnName: id
                nullable: true
                onDelete: CASCADE
            cascade: [ persist, remove ]

