Sil\Bundle\CRMBundle\Entity\Category:
    type: entity
    table: sil_crm_category
    fields: ~

    oneToMany:
        organisms:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            mappedBy: category
            cascade: [ persist ]
