Sil\Bundle\CRMBundle\Entity\City:
    type: mappedSuperclass
    table: sil_crm_city

    indexes:
        sil_crm_city_country_index:
            columns: [ country_code ]
        sil_crm_city_zip_index:
            columns: [ zip ]
        sil_crm_city_city_index:
            columns: [ city ]

    fields:
        country_code:
            type:       string(2)
            nullable:   false
        zip:
            type:       string(20)
            nullable:   false
        city:
            type:       string(255)
            nullable:   false
        insee_code:
            type:       string(20)
            nullable:   true
        lat:
            type:       float
            nullable:   true
        lng:
            type:       float
            nullable:   true
