Sil\Bundle\CRMBundle\Entity\Country:
    type: mappedSuperclass
    table: sil_crm_country
    fields:
        code:
            type: string
            length: 2
            unique: true
        enabled:
            type: boolean

    oneToMany:
        provinces:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Province
            mappedBy: country
            orphanRemoval: true
            cascade: [ all ]
            orderBy: { 'name': 'ASC' }

    indexes:
        sil_crm_country_code_index:
            columns: [ code ]
