Sil\Bundle\CRMBundle\Entity\OrganismPhone:
    type: mappedSuperclass
    table: sil_crm_organism_phone
    manyToOne:
        organism:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: phones
            joinColumn:
                name: organism_id
            cascade: [ persist ]
