Librinfo\CRMBundle\Entity\Organism:
    type: entity
    repositoryClass: Librinfo\CRMBundle\Entity\Repository\OrganismRepository
    inheritanceType: JOINED
    discriminatorColumn:
        name: discriminator
        type: string
    fields:
        url:
            type:       string
            length:     255
            nullable:   true
        administrativeNumber:
            type:       string
            length:     255
            nullable:   true
        individual:
            type: boolean
            options:
                default: false
        customer:
            type: boolean
            options:
                default: false
        customerCode:
            type:       string
            length:     255
            nullable:   true
        supplier:
            type: boolean
            options:
                default: false
        supplierCode:
            type:       string
            length:     255
            nullable:   true
        iban:
            type:       string
            length:     255
            nullable:   true
        vat:
            type:       string
            length:     255
            nullable:   true
        vatVerified:
            type: smallint
            options:
                default: 0
        alert:
            type:       string
            length:     255
            nullable:   true
        active: 
            type:       boolean
        catalogue_sent:
            type:       boolean
            nullable:   true
        last_catalogue_sent_date:
            type:       date
            nullable:   true
        first_catalogue_sent_date:
            type:       date
            nullable:   true
        catalogue_send_mean:
            type: text
            nullable: true
        source:
            type: text
            nullable: true

    oneToMany:
        phones:
            targetEntity: OrganismPhone
            mappedBy: organism
            cascade: [ persist, remove ]
            orphanRemoval: true
        positions:
            targetEntity: Position
            mappedBy: organism
            cascade: [ persist, remove ]
            orphanRemoval: true

    manyToMany:
        circles:
            targetEntity: Librinfo\CRMBundle\Entity\Circle
            inversedBy: organisms
            joinTable:
                name: ~
                joinColumns:
                    circle_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    organism_id:
                        referencedColumnName: id

    manyToOne:
        category:
            targetEntity: Librinfo\CRMBundle\Entity\Category
            inversedBy: organisms
            joinColumn:
                name: category_id
                onDelete: set null
            cascade: [ persist ]

