Sil\Bundle\CRMBundle\Entity\OrganismPhone:
    type: entity
    manyToOne:
        organism:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: phones
            joinColumn:
                name: organism_id
            cascade: [ persist ]
