Sil\Bundle\CRMBundle\Entity\OrganismGroup:
    type:  entity
    manyToOne:
        organism:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Organism
            joinColumn:
                name: organism_id
                referencedColumnName: id
    manyToMany:
        roles:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Role
            inversedBy: contactGroups
            joinTable:
                name: ~
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    organism_group_id:
                        referencedColumnName: id
