Sil\Bundle\CRMBundle\Entity\OrganismGroup:
    type:  entity
    table: sil_crm_organism_group
    manyToOne:
        organism:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            joinColumn:
                name: organism_id
                referencedColumnName: id
    manyToMany:
        roles:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Role
            inversedBy: contactGroups
            joinTable:
                name: sil_crm_organsim_group__role
                joinColumns:
                    role_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    organism_group_id:
                        referencedColumnName: id
