Sil\Bundle\CRMBundle\Entity\Organism:
    type: mappedSuperclass
    repositoryClass: Sil\Bundle\CRMBundle\Entity\Repository\OrganismRepository
    blast:
        loggable: true

    oneToOne:
        defaultAddress:
            targetEntity: Sil\Bundle\CRMBundle\Entity\AddressInterface
            joinColumn:
                name: default_address_id
                onDelete: SET NULL
            cascade: [persist, remove]
            orphanRemoval: true

    oneToMany:
        addresses:
            targetEntity: Sil\Bundle\CRMBundle\Entity\AddressInterface
            mappedBy: customer
            cascade: [ persist, remove ]
            orphanRemoval: true

    manyToMany:
        circles:
            orderBy: { 'code': 'ASC' }
            targetEntity: Sil\Bundle\CRMBundle\Entity\Circle
            inversedBy: organisms
            joinTable:
                name: ~
                joinColumns:
                    circle_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    organism_id:
                        referencedColumnName: id
