# user mapping
Sil\Bundle\CRMBundle\Entity\Phone:
    type: mappedSuperclass
    fields:
        number:
            type: string
            length: 255
        phoneType:
            type: string
            length: 255
            nullable: true

