Sil\Bundle\CRMBundle\Entity\Position:
    type: mappedSuperclass
    table: sil_crm_position
    fields:
        phone:
            type: string
            length: 255
            nullable: true
        department:
            type: string
            length: 255
            nullable: true
    manyToOne:
        individual:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: organizations
            joinColumn:
                name: individual_id
                referencedColumnName: id
                nullable: false
            cascade:
                - persist
            orphanRemoval: true
        organization:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismInterface
            inversedBy: individuals
            joinColumn:
                name: organization_id
                referencedColumnName: id
                nullable: false
            cascade:
                - persist
        positionType:
            targetEntity: Sil\Bundle\CRMBundle\Entity\PositionType
    manyToMany:
        circles:
            targetEntity: Sil\Bundle\CRMBundle\Entity\Circle
            inversedBy: positions
            joinTable:
                name: sil_crm_position__circle
                joinColumns:
                    position_id:
                        referencedColumnName: id
                inverseJoinColumns:
                    circle_id:
                        referencedColumnName: id


    lifecycleCallbacks: {  }
