Sil\Bundle\CRMBundle\Entity\Role:
    type: entity
    fields: ~
    manyToMany:
        contactGroups:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismGroup
            mappedBy: roles

