Sil\Bundle\CRMBundle\Entity\Role:
    type: mappedSuperclass
    table: sil_crm_role
    fields: ~
    manyToMany:
        contactGroups:
            targetEntity: Sil\Bundle\CRMBundle\Entity\OrganismGroup
            mappedBy: roles
