imports:
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism_embedded.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.individual.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organization.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.customer.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism_phone.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.category.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.role.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.organism_group.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.circle.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.position.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.position_type.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.phone_type.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.city.yml" }
    - { resource: "@SilCRMBundle/Resources/config/admin/sil_crm.admin.address.yml" }
