services:
    librinfo_crm.admin.contact:
        class: Librinfo\CRMBundle\Admin\ContactAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo


    librinfo_crm.admin.contact_embedded:
        class: Librinfo\CRMBundle\Admin\ContactEmbeddedAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Contact, SonataAdminBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: librinfo.crm.contact_embedded_admin.label
              label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.organism:
        class: Librinfo\CRMBundle\Admin\OrganismAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]
    
    librinfo_crm.admin.customer:
        class: Librinfo\CRMBundle\Admin\CustomerAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Organism, LibrinfoCRMBundle:OrganismAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo
        calls:
            - [setManager, [@doctrine.orm.entity_manager]]
            - [setCodeGenerator, [@librinfo_crm.code_generator.customer]]
            - [ setTemplate, [edit, LibrinfoCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, LibrinfoCRMBundle:OrganismAdmin:show.html.twig]]

    librinfo_crm.admin.organismphone:
        class: Librinfo\CRMBundle\Admin\OrganismPhoneAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\OrganismPhone, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.organism_phone_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.category:
        class: Librinfo\CRMBundle\Admin\CategoryAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Category, BlastCoreBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.category_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.role:
        class: Librinfo\CRMBundle\Admin\RoleAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Role, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.role_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.contactgroup:
        class: Librinfo\CRMBundle\Admin\ContactGroupAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\ContactGroup, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_group_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.contactphone:
        class: Librinfo\CRMBundle\Admin\ContactPhoneAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\ContactPhone, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.contact_phone_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.circle:
        class: Librinfo\CRMBundle\Admin\CircleAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Circle, LibrinfoCRMBundle:CircleAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.circle_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.position:
        class: Librinfo\CRMBundle\Admin\PositionAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\Position, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.position_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.position_type:
        class: Librinfo\CRMBundle\Admin\PositionTypeAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\PositionType, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.position_type_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.phone_type:
        class: Librinfo\CRMBundle\Admin\PhoneTypeAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\PhoneType, SonataAdminBundle:CRUD]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.phone_type_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.city:
        class: Librinfo\CRMBundle\Admin\CityAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\City, LibrinfoCRMBundle:CityAdmin]
        tags:
            -   name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: librinfo.crm.city_admin.label
                label_translator_strategy: blast_core.label.strategy.librinfo

    librinfo_crm.admin.contact_search_index:
        class: Librinfo\CRMBundle\Admin\ContactSearchIndexAdmin
        arguments: [~, Librinfo\CRMBundle\Entity\ContactSearchIndex, BlastCoreBundle:CRUD]
        tags:
            - name: sonata.admin
              manager_type: orm
              group: admin
              label: ContactSearchIndex
            
