services:
#    crm.example:
#        class: Librinfo\CRMBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]

    security.access.circle_voter:
        class:      Librinfo\CRMBundle\Security\Authorization\Voter\CircleVoter
        public:     false
        tags:
            - { name: security.voter }

    sonata.admin.exporter:
        class: Librinfo\CRMBundle\Admin\Exporter
        calls:
            - [setTokenStorage, ['@security.token_storage']]
            - [setTranslator, ['@translator']]
            - [setTwig, ['@twig']]
            - [setRouter, ['@router']]

### DOCTRINE MAPPING ###

    librinfo.crm.listener.email_bundle:
        class: Librinfo\CRMBundle\EventListener\EmailBundleListener
        tags:
            - { name: doctrine.event_subscriber }
        calls:
            - [setLogger,[@logger]]
            - [setBundles, [%kernel.bundles%]]
            - [setClassAnalyser, [Librinfo\CoreBundle\Tools\Reflection\ClassAnalyzer]]
