Sil\Bundle\CRMBundle\Entity\Contact:
    constraints:
        - Callback: validateName

Sil\Bundle\CRMBundle\Entity\Organism:
    properties:
        iban:
            - Iban:
                message: This is not a valid International Bank Account Number (IBAN).
        positions:
            - Valid: ~
        email:
            - NotNull:
                groups: [librinfo_ecommerce_organism]
            - Email:
                groups: [librinfo_ecommerce_organism]

Sil\Bundle\CRMBundle\Entity\Position:
    properties:
        individual:
            - Valid: ~

Sil\Bundle\CRMBundle\Entity\Address:
    properties:
        organism:
            - Valid: ~
        firstName:
            - NotNull:
                groups: [librinfo_ecommerce_address]
        lastName:
            - NotNull:
                groups: [librinfo_ecommerce_address]
        postCode:
            - NotNull:
                groups: [librinfo_ecommerce_address]
        city:
            - NotNull:
                groups: [librinfo_ecommerce_address]
        street:
            - NotNull:
                groups: [librinfo_ecommerce_address]
