
services:
    sil_crm.admin.category:
        class: Sil\Bundle\CRMBundle\Admin\CategoryAdmin
        arguments: [~, "%sil_crm.entity.category.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.category
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
