
services:
    sil_crm.admin.role:
        class: Sil\Bundle\CRMBundle\Admin\RoleAdmin
        arguments: [~, "%sil_crm.entity.role.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.role
                label_translator_strategy: blast_core.label.strategy.sil_crm
