
services:
    sil_crm.admin.role:
        class: Sil\Bundle\CRMBundle\Admin\RoleAdmin
        arguments: [~, "%sil.model.crm_role.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.role
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
