
services:
    sil_crm.admin.position_type:
        class: Sil\Bundle\CRMBundle\Admin\PositionTypeAdmin
        arguments: [~, "%sil.model.crm_position_type.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.position_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
