
services:
    sil_crm.admin.phone_type:
        class: Sil\Bundle\CRMBundle\Admin\PhoneTypeAdmin
        arguments: [~, "%sil_crm.entity.phone_type.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.phone_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
