
services:
    sil_crm.admin.circle:
        class: Sil\Bundle\CRMBundle\Admin\CircleAdmin
        arguments: [~, '%sil_crm.entity.circle.class%', SilCRMBundle:CircleAdmin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.circle
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
