
services:
    sil_crm.admin.customer:
        class: Sil\Bundle\CRMBundle\Admin\CustomerAdmin
        arguments: [~, "%sil_crm.entity.organism.class%", SilCRMBundle:OrganismAdmin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.customer
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
        calls:
            - [ setCodeGenerator, ['@sil_crm.code_generator.customer'] ]
            - [ setTemplate, [edit, SilCRMBundle:OrganismAdmin:edit.html.twig] ]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig] ]
