
services:
    sil_crm.admin.organism:
        class: Sil\Bundle\CRMBundle\Admin\OrganismAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\OrganismInterface, SilCRMBundle:OrganismAdmin]
        services:
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.organism
                label_translator_strategy: blast_core.label.strategy.sil_crm
        calls:
            - [ setTemplate, [edit, SilCRMBundle:OrganismAdmin:edit.html.twig]]
            - [ setTemplate, [show, SilCRMBundle:OrganismAdmin:show.html.twig]]
