
services:
    sil_crm.admin.organism_embedded:
        class: Sil\Bundle\CRMBundle\Admin\OrganismEmbeddedAdmin
        arguments: [~, "%sil_crm.entity.organism.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.crmbundle.admin.organism_embedded
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
