
services:
    sil_crm.admin.organism_embedded:
        class: Sil\Bundle\CRMBundle\Admin\OrganismEmbeddedAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\Organism, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: admin
                label: sil.crmbundle.admin.organism_embedded
                label_translator_strategy: blast_core.label.strategy.sil_crm
