
services:
    sil_crm.admin.circle:
        class: Sil\Bundle\CRMBundle\Admin\CircleAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\Circle, SilCRMBundle:CircleAdmin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.circle
                label_translator_strategy: blast_core.label.strategy.sil_crm
