
services:
    sil_crm.admin.position:
        class: Sil\Bundle\CRMBundle\Admin\PositionAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\Position, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.position
                label_translator_strategy: blast_core.label.strategy.sil_crm
