
services:
    sil_crm.admin.position:
        class: Sil\Bundle\CRMBundle\Admin\PositionAdmin
        arguments: [~, "%sil.model.crm_position.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.position
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
