
services:
    sil_crm.admin.phone_type:
        class: Sil\Bundle\CRMBundle\Admin\PhoneTypeAdmin
        arguments: [~, "%sil.model.crm_phone_type.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.phone_type
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
