
services:
    sil_crm.admin.organism_group:
        class: Sil\Bundle\CRMBundle\Admin\OrganismGroupAdmin
        arguments: [~, "%sil_crm.entity.organism_group.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.organism_group
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
