
services:
    sil_crm.admin.phone_type:
        class: Sil\Bundle\CRMBundle\Admin\PhoneTypeAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\PhoneType, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.phone_type
                label_translator_strategy: blast_core.label.strategy.sil_crm
