
services:
    sil_crm.admin.city:
        class: Sil\Bundle\CRMBundle\Admin\CityAdmin
        arguments: [~, "%sil.model.crm_city.class%", SilCRMBundle:CityAdmin]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.city
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
