
services:
    sil_crm.admin.category:
        class: Sil\Bundle\CRMBundle\Admin\CategoryAdmin
        arguments: [~, Sil\Bundle\CRMBundle\Entity\Category, BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crmbundle.admin.category
                label_translator_strategy: blast_core.label.strategy.sil_crm
