
services:
    sil_crm.admin.organism_phone:
        class: Sil\Bundle\CRMBundle\Admin\OrganismPhoneAdmin
        arguments: [~, "%sil.model.crm_organism_phone.class%", BlastCoreBundle:CRUD]
        tags:
            -
                name: sonata.admin
                manager_type: orm
                group: Customers Relationship Management
                label: sil.crm.menu_label.organism_phone
                label_translator_strategy: blast.resource.sonata.label_strategy.prefix
