<?php

namespace Librinfo\CRMBundle\Entity\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-29 at 15:57:06.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\CRMBundle\Entity\Category;


class CategoryTest extends TestCase
{
    /**
     * @var Category
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
    /*
    * @todo: uncomment this line
    * $this->object = new Category;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::addOrganism
     * @todo   Implement testAddOrganism().
     */
    public function testAddOrganism()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::removeOrganism
     * @todo   Implement testRemoveOrganism().
     */
    public function testRemoveOrganism()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getOrganisms
     * @todo   Implement testGetOrganisms().
     */
    public function testGetOrganisms()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::isNew
     * @todo   Implement testIsNew().
     */
    public function testIsNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setTreeLft
     * @todo   Implement testSetTreeLft().
     */
    public function testSetTreeLft()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeLft
     * @todo   Implement testGetTreeLft().
     */
    public function testGetTreeLft()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setTreeRgt
     * @todo   Implement testSetTreeRgt().
     */
    public function testSetTreeRgt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeRgt
     * @todo   Implement testGetTreeRgt().
     */
    public function testGetTreeRgt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setTreeLvl
     * @todo   Implement testSetTreeLvl().
     */
    public function testSetTreeLvl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeLvl
     * @todo   Implement testGetTreeLvl().
     */
    public function testGetTreeLvl()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::addTreeChild
     * @todo   Implement testAddTreeChild().
     */
    public function testAddTreeChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::removeTreeChild
     * @todo   Implement testRemoveTreeChild().
     */
    public function testRemoveTreeChild()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeChildren
     * @todo   Implement testGetTreeChildren().
     */
    public function testGetTreeChildren()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setTreeRoot
     * @todo   Implement testSetTreeRoot().
     */
    public function testSetTreeRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeRoot
     * @todo   Implement testGetTreeRoot().
     */
    public function testGetTreeRoot()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::setTreeParent
     * @todo   Implement testSetTreeParent().
     */
    public function testSetTreeParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::getTreeParent
     * @todo   Implement testGetTreeParent().
     */
    public function testGetTreeParent()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Category::initCollections
     * @todo   Implement testInitCollections().
     */
    public function testInitCollections()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
