<?php

namespace Librinfo\CRMBundle\Entity\Test\Unit;

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-29 at 10:30:10.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\CRMBundle\Entity\Contact;


class ContactTest extends TestCase
{
    /**
     * @var Contact
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
      $this->object = new Contact;

    /*
    * @todo: uncomment this line
    * $this->object = new Contact;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setFirstname
     * @todo   Implement testSetFirstname().
     */
    public function testSetFirstname()
    {
      $test=$this->object->setFirstname('ali');
      $this->assertNotEquals($test,'ali');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getFirstname
     * @todo   Implement testGetFirstname().
     */
    public function testGetFirstname()
    {
      $firstname=$this->object->setFirstname('ali');
      $test=$this->object->getFirstname();
      $this->assertEquals($test,'ali');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setShortname
     * @todo   Implement testSetShortname().
     */
    public function testSetShortname()
    {
      $shortname=$this->object->setShortname('pirlos');
      $this->assertFalse($shortname==='pirlos');
/* @todo : find a good way to check result */
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getShortname
     * @covers Librinfo\CRMBundle\Entity\Contact::setShortname
     * @todo   Implement testGetShortname().
     */
    public function testGetShortname()
    {
      $this->object->setShortname('ali');
      $test = $this->object->getShortname();
      $this->assertTrue($test==='ali');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setTitle
     * @todo   Implement testSetTitle().
     */
    public function testSetTitle()
    {
      $title=$this->object->setTitle('Ambassadeurs');
      $this->assertFalse($title==='pirlos');
      $this->assertTrue($title!=='Ambassadeurs');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getTitle
     * @todo   Implement testGetTitle().
     */
    public function testGetTitle()
    {
      $title=$this->object->setTitle('Ambassadeurs');
      $test = $this->object->getTitle();
      $this->assertFalse($test!=='Ambassadeurs');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setFlashOnControl
     * @todo   Implement testSetFlashOnControl().
     */
    public function testSetFlashOnControl()
    {
      $flashOnControl=$this->object->setFlashOnControl('cc');
      $this->assertFalse($flashOnControl==='aa');
      $this->assertFalse($flashOnControl==='Cc');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getFlashOnControl
     * @todo   Implement testGetFlashOnControl().
     */
    public function testGetFlashOnControl()
    {
      $flashOnControl=$this->object->setFlashOnControl('cc');
      $test = $this->object->getFlashOnControl();
      $this->assertFalse($test==='Ambassadeurs');

    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setPassword
     * @todo   Implement testSetPassword().
     */
    public function testSetPassword()
    {
      $password=$this->object->setPassword('secret');
      $this->assertFalse($password === 'ssecret');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getPassword
     * @todo   Implement testGetPassword().
     */
    public function testGetPassword()
    {
      $password=$this->object->setPassword('secret');
      $test=$this->object->getPassword();
      $this->assertTrue($test === 'secret');
      $this->assertFalse($test === 'ali');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setFamilyContact
     * @todo   Implement testSetFamilyContact().
     */
    public function testSetFamilyContact()
    {
      $familyContact=$this->object->setFamilyContact('mam');
      $this->assertFalse($familyContact === 'secret');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getFamilyContact
     * @todo   Implement testGetFamilyContact().
     */
    public function testGetFamilyContact()
    {
      $this->object->setFamilyContact('mam');
      $test=$this->object->getFamilyContact();
      $this->assertEquals($test,'mam');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setCulture
     * @todo   Implement testSetCulture().
     */
    public function testSetCulture()
    {
      $culture=$this->object->setCulture('Culture');
      $this->assertFalse($culture === 'secret');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getCulture
     * @todo   Implement testGetCulture().
     */
    public function testGetCulture()
    {
      $culture=$this->object->setCulture('Culture');
      $test=$this->object->getCulture();
      $this->assertTrue($test === 'Culture');
      $this->assertFalse($test !== 'Culture');
      $this->assertEquals($test,'Culture');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::initCollections
     * @todo   Implement testInitCollections().
     */
    public function testInitCollections()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::__clone
     * @todo   Implement test__clone().
     */
    public function test__clone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::addPhone
     * @todo   Implement testAddPhone().
     */
    public function testAddPhone()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
          'This test has not been implemented yet.'
      );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::removePhone
     * @todo   Implement testRemovePhone().
     */
    public function testRemovePhone()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getPhones
     * @todo   Implement testGetPhones().
     */
    public function testGetPhones()
    {

        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::__toString
     * @todo   Implement test__toString().
     */
    public function test__toString()
    {
      $this->object->setFirstname('ali');
      $this->object->setName('tal');
      $this->object->getFirstname();
      $this->object->getName();
      $test=$this->object->__toString();
      $this->assertEquals($test,'ali tal');

    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::isPersonal
     * @todo   Implement testIsPersonal().
     */
    public function testIsPersonal()
    {
      $test=$this->object->isPersonal();
      $this->assertEquals($test,true);
      $this->assertNotEquals($test,false);
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getFulltextName
     * @todo   Implement testGetFulltextName().
     */
    public function testGetFulltextName()
    {
      $this->object->setTitle('Ambassadeurs');
      $this->object->getTitle();
      $this->object->setFirstname('martiN');
      $this->object->getFirstname();
      $this->object->setName('tal');
      $this->object->getName();
      $test=$this->object->getFulltextName();
      $this->assertEquals($test,'Ambassadeurs Martin TAL');
      $this->assertNotEquals($test,'AmbassadeurT Martin TAL');
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::validateName
     * @todo   Implement testValidateName().
     */
    public function testValidateName()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getId
     * @todo   Implement testGetId().
     */
    public function testGetId()
    {
      $this->assertTrue($this->object->getId()===null);

    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setId
     * @todo   Implement testSetId().
     */
    public function testSetId()
    {
      $this->assertTrue($this->object->setId(45)!==null);
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::isNew
     * @todo   Implement testIsNew().
     */
    public function testIsNew()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setName
     * @todo   Implement testSetName().
     */
    public function testSetName()
    {
      $test=$this->object->setName('ahamada');
      $this->assertTrue($test!=='ahamada');

    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getName
     * @todo   Implement testGetName().
     */
    public function testGetName()
    {
      $this->object->setName('ahamada');
      $test=$this->object->getName();
      $this->assertTrue($test==="ahamada");
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getCreatedAt
     * @todo   Implement testGetCreatedAt().
     */
    public function testGetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setCreatedAt
     * @todo   Implement testSetCreatedAt().
     */
    public function testSetCreatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getUpdatedAt
     * @todo   Implement testGetUpdatedAt().
     */
    public function testGetUpdatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setUpdatedAt
     * @todo   Implement testSetUpdatedAt().
     */
    public function testSetUpdatedAt()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getEmail
     * @todo   Implement testGetEmail().
     */
    public function testGetEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setEmail
     * @todo   Implement testSetEmail().
     */
    public function testSetEmail()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::isEmailNpai
     * @todo   Implement testIsEmailNpai().
     */
    public function testIsEmailNpai()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setEmailNpai
     * @todo   Implement testSetEmailNpai().
     */
    public function testSetEmailNpai()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::isEmailNoNewsletter
     * @todo   Implement testIsEmailNoNewsletter().
     */
    public function testIsEmailNoNewsletter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setEmailNoNewsletter
     * @todo   Implement testSetEmailNoNewsletter().
     */
    public function testSetEmailNoNewsletter()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::addPosition
     * @todo   Implement testAddPosition().
     */
    public function testAddPosition()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::removePosition
     * @todo   Implement testRemovePosition().
     */
    public function testRemovePosition()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
          'This test has not been implemented yet.'
      );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getPositions
     * @todo   Implement testGetPositions().
     */
    public function testGetPositions()
    {
      $this->assertTrue($this->object->getPositions()!==ArrayCollection::class);
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::addCircle
     * @todo   Implement testAddCircle().
     */
    public function testAddCircle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::removeCircle
     * @todo   Implement testRemoveCircle().
     */
    public function testRemoveCircle()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getCircles
     * @todo   Implement testGetCircles().
     */
    public function testGetCircles()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setDescription
     * @todo   Implement testSetDescription().
     */
    public function testSetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getDescription
     * @todo   Implement testGetDescription().
     */
    public function testGetDescription()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::addSearchIndex
     * @todo   Implement testAddSearchIndex().
     */
    public function testAddSearchIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::removeSearchIndex
     * @todo   Implement testRemoveSearchIndex().
     */
    public function testRemoveSearchIndex()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getSearchIndexes
     * @todo   Implement testGetSearchIndexes().
     */
    public function testGetSearchIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::setSearchIndexes
     * @todo   Implement testSetSearchIndexes().
     */
    public function testSetSearchIndexes()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::analyseField
     * @todo   Implement testAnalyseField().
     */
    public function testAnalyseField()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::initAddresses
     * @todo   Implement testInitAddresses().
     */
    public function testInitAddresses()
    {
      $test=$this->object->initAddresses();
      $this->assertFalse(ArrayCollection::class===$test);
      $this->assertTrue(Collection::class!==$test);
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::addAddress
     * @todo   Implement testAddAddress().
     */
    public function testAddAddress()
    {
      // Remove the following lines when you implement this test.
      $this->markTestIncomplete(
          'This test has not been implemented yet.'
      );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::removeAddress
     * @todo   Implement testRemoveAddress().
     */
    public function testRemoveAddress()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Librinfo\CRMBundle\Entity\Contact::getAddresses
     * @todo   Implement testGetAddresses().
     */
    public function testGetAddresses()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
