parameters:
    librinfo.crmbundle.datafixtures:
        user:
            username: 'SDW'
            password: 'testSDW'
            email: 'testSDW@test.fr'
            role: 'ROLE_GLOBAL_TEST'
        organism:
            name: 'Librinfo'
            administrative_number: 1000
            url : 'https://github.com/libre-informatique/'
        category:
            name: 'First category'
        contact:
            title: 'title contact'
        role:
            name: 'Responsable'
