blast_base_entities:
    entity_searchable_indexes:
        -
            class: "%sil_crm.entity.organism.class%"
            fields:
                - name
                # - fulltextName
                - firstname
                - lastname
                - description
                - email
                - url
        -
            class: "%sil_crm.entity.address.class%"
            fields:
                - lastName
                - firstName
                - postCode
                - street
                - city
                - countryCode
                - provinceCode
                - provinceName
        -
            class: "%sil_crm.entity.position.class%"
            fields:
                - label
                - description
                - email
                - department
