<?php

/*
 * This file is part of the Blast Project package.
 *
 * Copyright (C) 2015-2017 Libre Informatique
 *
 * This file is licenced under the GNU LGPL v3.
 * For the full copyright and license information, please view the LICENSE.md
 * file that was distributed with this source code.
 */

namespace Librinfo\CRMBundle\Admin\Test\Unit;

/*
 * Generated by PHPUnit_SkeletonGenerator on 2017-06-30 at 16:06:41.
 */

use PHPUnit\Framework\TestCase;
use Librinfo\CRMBundle\Admin\CustomerAdmin;

class CustomerAdminTest extends TestCase
{
    /**
     * @var CustomerAdmin
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp()
    {
        /*
    * @todo: uncomment this line
    * $this->object = new CustomerAdmin;
    */
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown()
    {
    }

    /**
     * @covers \Librinfo\CRMBundle\Admin\CustomerAdmin::configureFormFields
     *
     * @todo   Implement testConfigureFormFields().
     */
    public function testConfigureFormFields()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Librinfo\CRMBundle\Admin\CustomerAdmin::createQuery
     *
     * @todo   Implement testCreateQuery().
     */
    public function testCreateQuery()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Librinfo\CRMBundle\Admin\CustomerAdmin::getNewInstance
     *
     * @todo   Implement testGetNewInstance().
     */
    public function testGetNewInstance()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }

    /**
     * @covers \Librinfo\CRMBundle\Admin\CustomerAdmin::setCodeGenerator
     *
     * @todo   Implement testSetCodeGenerator().
     */
    public function testSetCodeGenerator()
    {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
            'This test has not been implemented yet.'
        );
    }
}
